version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    image: anansilva/blog
    container_name: blog
    working_dir: /blog-rails
    entrypoint: './docker/dev-entrypoint.sh'
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog-rails
      - bundler_gems:/usr/local/bundle
      - yarn_cache:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: blog_dev
      POSTGRES_USER: blog_dev
      POSTGRES_DB: blog_development

volumes:
  postgres:
  bundler_gems:
  yarn_cache:
