default: &default
  adapter: postgresql
  pool: 5
  username: blog_dev
  password: blog_dev

development:
  <<: *default
  host: postgres
  database: blog_development

test:
  <<: *default
  host: db
  database: blog_test
