default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: blog_dev
  password: blog_dev
  pool: 5

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test
